services:
  app:
    container_name: gnome_app
    restart: unless-stopped
    build:
      context: .
      target: $DOCKERFILE_TARGET
    volumes:
      - gnome_data:/app/
      - .:/app
    depends_on:
      - redis
      - worker_beat
    ports:
      - "8000:8000"
    env_file: docker.env
    networks:
      - gnome_net

  worker_beat:
    restart: unless-stopped
    build:
      context: .
      target: worker
    command: ["/bin/sh", "-c", "celery -A core  worker -l info --concurrency=1"]
    volumes:
      - gnome_data:/app/
      - .:/app
    env_file: docker.env
    networks:
      - gnome_net


  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - gnome_net



  redis:
    container_name: gnome_syncer_redis
    image: redis:alpine
    restart: always
    volumes:
      - gnome_data:/app/
    networks:
      - gnome_net

  flower:
    image: mher/flower
    command: ['celery', '--broker=redis://redis:6379', 'flower', '--port=5555', "--basic-auth=$FLOWER_USERNAME:$FLOWER_PASSWORD"]
    ports:
      - 7777:5555
    env_file: docker.env
    depends_on:
      - redis
    networks:
      - gnome_net


volumes:
  gnome_data:
    driver: local
  pg_data:
    driver: local

networks:
  gnome_net:
    driver: bridge
    name: gnome_net
